### ISSUE TITLE
VPC lambda timeout failure

### ISSUE THREAD

**Issue by BastLeblanc** [aws-cloudformation/custom-resource-helper#34]
Hi,

The behavior for a in-VPC Lambda function with no internet access lacks error messages and timeout.

- there's no timeout, it should try (eventually retry) and fail with an error message, here:

https://github.com/aws-cloudformation/custom-resource-helper/blob/006d4e92ebba11c2b1635962262b12f00983416c/crhelper/utils.py#L25

- It should be clear (documentation and error message) that the Lambda function needs access to S3 to report the status, by either full internet access or by having an S3 endpoint in the VPC

Bastien(AWS)

**Comment by ptc-jpompe** [comment]
If you add a timeout to the connection it will at least show some errors in the logs.

```
[ERROR]	...	Unexpected failure sending response to CloudFormation timed out
Traceback (most recent call last):
  File "/var/task/crhelper/utils.py", line 28, in _send_response
    connection.request(method="PUT", url=url, body=json_response_body, headers=headers)
  File "/var/lang/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/var/lang/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/var/lang/lib/python3.8/http/client.py", line 1392, in connect
    super().connect()
  File "/var/lang/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/var/lang/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/var/lang/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```
